---
- name: Add Jenkins key
  apt_key: 
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present  

- name: Ensure Jenkins repo is available
  apt_repository: 
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present  

- name: Install Jenkins
  apt: 
    name: jenkins 
    state: present

- name: Add jenkins to group sudo
  user: 
    name: jenkins
    groups: docker
    append: yes   

- name: Copy Jenkins config.xml
  copy:
    src: "{{ role_path }}/files/config.xml"
    dest: /var/lib/jenkins/config.xml

- name: Copy Jenkins credentials.xml
  copy:
    src: "{{ role_path }}/files/credentials.xml"
    dest: /var/lib/jenkins/credentials.xml  

- name: Create college-app-tracker-jenkins job directory
  file: path=/var/lib/jenkins/jobs/college-app-tracker-jenkins state=directory mode=0755

- name: Copy college-app-tracker-jenkins job config.xml
  copy:
    src: "{{ role_path }}/files/college-app-tracker-jenkins-job.xml"
    dest: /var/lib/jenkins/jobs/college-app-tracker-jenkins/config.xml  



