--- 
- name: Ensure repository key is installed
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: Ensure JDK repo is available
  apt_repository: 
    repo: 'ppa:openjdk-r/ppa' 
    state: present

- name: Install JDK
  apt: name={{item}} state=present
  with_items:
    - openjdk-8-jdk