---
- name: Create Jenkins directory
  file: 
    path: /opt/jenkins 
    state: directory 
    owner: 1000
    group: 1000

- name: Copy Jenkins docker-compose file
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /home/ubuntu  

- name: Launch ealberto/jenkins Docker container
  command: "docker-compose up"