---
- name: Setup CI Servers
  hosts: ci_servers
  vars: 
    nodejs_version: 8.x
  remote_user: ubuntu
  become: yes
  
  roles:
    - base      
    - python-pip
    - docker 
    - jenkins-docker

- name: Copy inventory file in Jenkins
- hosts: ci_servers
  user: ubuntu
  tasks:
  copy:
    src: "iventory"
    dest: /home/ubuntu  
