---
- hosts: ci_servers
  user: ubuntu
  tasks:
    - name: generate ssh keys
      user:
        name: ubuntu
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: fetch public key
      fetch:
        src: ~/.ssh/id_rsa.pub
        dest: tmp/
        flat: yes

    - name: create ssh config file
      copy:
        content: "StrictHostKeyChecking no"
        dest: "~/.ssh/config"

- hosts: web_servers
  remote_user: ubuntu
  tasks:
    - name: add master public key to slaves
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', 'tmp/id_rsa.pub') }}"