---
- hosts: ci_master
  user: ubuntu
  tasks:
    - name: generate ssh keys
      user:
        name: ubuntu
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: fetch public key
      fetch:
        src: ~/.ssh/id_rsa.pub
        dest: tmp/master/id_rsa.pub
        flat: yes

    - name: create ssh config file
      copy:
        content: "StrictHostKeyChecking no"
        dest: "~/.ssh/config"

# For now assume there's only one worker
- hosts: ci_workers
  user: ubuntu
  tasks:
    - name: generate ssh keys
      user:
        name: ubuntu
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: fetch public key
      fetch:
        src: ~/.ssh/id_rsa.pub
        dest: tmp/worker/id_rsa.pub
        flat: yes

    - name: create ssh config file
      copy:
        content: "StrictHostKeyChecking no"
        dest: "~/.ssh/config"        

- hosts: web_servers
  remote_user: ubuntu
  tasks:
    - name: add master public key to webservers
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', 'tmp/master/id_rsa.pub') }}"
    - name: add worker public key to webservers
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', 'tmp/worker/id_rsa.pub') }}"        

# For now assume there's only one worker
- hosts: ci_workers
  remote_user: ubuntu
  tasks:
    - name: add master public key to workers
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', 'tmp/master/id_rsa.pub') }}" 
