---
- name: Install Packages
  hosts: web_servers
  remote_user: ubuntu
  tasks:    
    - name: Ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present
      become: yes
        
    - name: Ensure docker registry is available
      # For Ubuntu 16.04 LTS, use this repo instead:
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
      become: yes

    - name: Add JDK Repository
      apt_repository: repo='ppa:openjdk-r/ppa' state=present
      become: yes

    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
      become: yes

    - name: Install packages
      apt: name={{item}} state=present
      become: yes
      with_items:
        - openjdk-8-jdk
        - git
        - python
        - docker-engine

    - service: name=docker state=restarted
      become: yes
