---
- name: Restart server
  shell: sleep 2 && /sbin/shutdown -r now "RedHat system package upgraded"
  become: yes
  async: 1
  poll: 0

- name: Wait 60 seconds for server to come back
  become: false
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=120
